on:
  push:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      # - run: powershell Compress-Archive build\windows\runner\release windows-release.zip
      - uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: build\windows\runner\release
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter build apk --split-per-abi --release
      # - run: powershell Compress-Archive build\windows\runner\release windows-release.zip
      - uses: actions/upload-artifact@v2
        with:
          name: android-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: android-armeabi-v7a-release
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: android-x86_64-release
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk 